<<<<<<< HEAD
env:
  es6: true
  browser: true
  commonjs: true
=======
parserOptions:
  sourceType: 'module'
  ecmaVersion: 2015

env:
  es6: true
  browser: true
>>>>>>> 98f666084e401c3d751e09d6d9de57c65a7162b6

extends: 'htmlacademy/es6'
